appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: iME/OdHsQdqxa1w55tb0Md6cEmqXN6DtDp3fIlidPZ7K8wtGC2w9EFnQMJ4hakLxASaUjY+q9UYu3yeup3UvD+FVEWQ4/5hqmjTiYlWbwfrWmtoxsUSNKJmUud49zD0YlfCqLqEkFuu8nMuPwj1naKgN7GFC7o/ciR+gABRvA+SxL8Qy2wUbiv4UEshzVTlwUbD+GZ0oxY5jaxVp+bSgtHTle4DHZtto/0WeNPdz/p2rn6K/zmc2EdDEM0nIyOq8zdv1ZGIxDcLRSLeLYyHEmWRfZfmEXqAQtNIFyWkU6Fi8KdW27vFOmzSy3oSOvLvMMq3Sng9YBTT98e5G5T7dQDnb9NnPtXg+igkqbZQy4Yu0pAvEiGjgMireytfmCOzXUAcAJjzeHizcpblk81HJJuQmTt7PZDpPacmNRq9kS3GxhUzoU2avukRHDgpNXMKOnhDTFkTvzcnyT/Fdg25qnXU19LIMkQ+de+FD+0pSr0IuQEjsAZ4l5e6xbWskRowX856tSC0t+p+uMJoXTfwQoj6yF+nITHTXBc7Upc/p/a+OzQ1unN0r2/zdqhNj5u83v5Hzbfw5UFcWc90Aja47Vczb3BTPpdS9BFwqFzqZMp+kTD35SdCM8fkkNcXqRvgldQ/HYEUzk1mG1swbBCdvtETRKgTTY8qF8ikXlqhgcdk=}
